# -*- coding: utf-8 -*-
"""z distr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ai8R4ZmGyB4CzE4EVJNaq-2ltNyUWQSB
"""

import numpy as np
from scipy import stats

# Given data
sample_mean = 78
pop_mean = 80
sample_std = 2.5
n = 40
alpha = 0.05

# Calculate standard error and z-score
se = sample_std / np.sqrt(n)
z_score = (sample_mean - pop_mean) / se

# Calculate p-value (two-tailed)
p_value = 2 * stats.norm.cdf(-abs(z_score))  # Multiply by 2 for two-tailed test

# Critical z-value
z_critical = stats.norm.ppf(1 - alpha/2)

print(f"Z-score: {z_score:.4f}")
print(f"P-value: {p_value:.10f}")
print(f"Critical z-value: ±{z_critical:.4f}")

# Decision
if abs(z_score) > z_critical:
    print("Reject the null hypothesis: There is significant evidence the machine is not working properly.")
else:
    print("Fail to reject the null hypothesis: Not enough evidence the machine isn't working properly.")